# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1acf1b8649b01d79e5adaaca2629e30dda521ed5caf56df623e289fe627cc58b332aacfd7fcc75190ebf63aba80f53ce2820e616c14026a923e7ad0789de1b5c

test:
  secret_key_base: 6c141fa6324c180786dda6a2dc9bc25f269b276c0324f6c204a32a20969557e47d38344285422640ffeb132f10b218bd92e6ab0c9c5b0b530cff6fbf6f2902e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
